{
 "title": "Go服务监控",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "query": { "query": "label_values(go_info,job)" } },
   { "name": "interval", "query": "1m,2m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "Go monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\"} [$interval])"
    }
   ]
  },
  {
   "title": "Process memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "rss"
    }
   ]
  },
  {
   "title": "Go memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$job\"}",
     "legendFormat": "total alloc"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$job\"}",
     "legendFormat": "heap inuse"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"$job\"}",
     "legendFormat": "stack inuse"
    }
   ]
  },
  {
   "title": "Go routines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Open fds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\"}"
    }
   ]
  },
  { "title": "HTTP monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{job=\"$job\"} [$interval]))",
     "legendFormat": "{{method}} {{path}} total"
    },
    {
     "expr": "sum(increase(http_requests_total{job=\"$job\",status=~\"2..\"} [$interval]))",
     "legendFormat": "{{method}} {{path}} 2xx"
    },
    {
     "expr": "sum(increase(http_requests_total{job=\"$job\",status=~\"4..\"} [$interval]))",
     "legendFormat": "{{method}} {{path}} 4xx"
    },
    {
     "expr": "sum(increase(http_requests_total{job=\"$job\",status=~\"5..\"} [$interval]))",
     "legendFormat": "{{method}} {{path}} 5xx"
    }
   ]
  },
  {
   "title": "Total qps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$job\"} [$interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(http_requests_total{job=\"$job\",status=~\"2..\"} [$interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(http_requests_total{job=\"$job\",status=~\"4..\"} [$interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(http_requests_total{job=\"$job\",status=~\"5..\"} [$__interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Detail request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{job=\"$job\",status=~\"2..\"} [$interval])) by (method, path)",
     "legendFormat": "2xx {{method}} {{path}}"
    },
    {
     "expr": "sum(increase(http_requests_total{job=\"$job\",status=~\"4..\"} [$interval])) by (method, path)",
     "legendFormat": "4xx {{method}} {{path}}"
    },
    {
     "expr": "sum(increase(http_requests_total{job=\"$job\",status=~\"5..\"} [$interval])) by (method, path)",
     "legendFormat": "5xx {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Detail qps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$job\",status=~\"2..\"} [$interval])) by (status, method, path)",
     "legendFormat": "2xx {{method}} {{path}}"
    },
    {
     "expr": "sum(rate(http_requests_total{job=\"$job\",status=~\"4..\"} [$interval])) by (status, method, path)",
     "legendFormat": "4xx {{method}} {{path}}"
    },
    {
     "expr": "sum(rate(http_requests_total{job=\"$job\",status=~\"5..\"} [$interval])) by (status, method, path)",
     "legendFormat": "5xx {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Response duraion (P90)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{job=\"$job\", status=~\"2..\"}[$interval])) by (le, method, path))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Response duraion (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"$job\", status=~\"2..\"}[$interval])) by (le, method, path))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  }
 ]
}