version: '3'

services:
  jaeger:
    platform: linux/arm64
    image: jaegertracing/all-in-one:1.48.0
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
    restart: no
